- name: "Deploy latest app"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "udacity-blog"
    CIRCLE_WORKFLOW_ID: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"
  tasks:
    - name: Update the deployment to run the latest Build
      shell: "./bin/kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}-app=703318274498.dkr.ecr.us-east-1.amazonaws.com/blog:{{ CIRCLE_WORKFLOW_ID }}"
      args:
        chdir: $HOME

    - name: Wait for pods to start running
      wait_for:
        timeout: 30

    - name: Check Pods
      shell: "./bin/kubectl get pods"
      args:
        chdir: $HOME
      register: get_pods
    
    - debug:
        var: get_pods.stdout_lines
    
    - name: Check services
      shell: "./bin/kubectl get services"
      args:
        chdir: $HOME
      register: get_services
      
    - debug:
        var: get_services.stdout_lines

    - name: Check if deployment is successful
      shell: "./bin/kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME
      register: check_deployment_status
      
    - debug:
        var: check_deployment_status.stdout_lines
