---
- name: "Download The AWS CLI Archive"
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  args:
    chdir: $HOME

- name: "Unzip the AWS CLI Archive"
  shell: unzip awscliv2.zip
  args:
    chdir: $HOME

- name: "Install the AWS CLI"
  shell: ./aws/install
  args:
    chdir: $HOME

- name: "Download kubectl"
  shell: curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.2/2023-10-17/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to a folder to the $PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME
