version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0

jobs:
  lint:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - restore_cache:
          keys: [install]
      - run:
          name: Lint app
          command: |
            npm install
            npm run lint
      - save_cache:
          paths: [node_modules]
          key: install
  
  test:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - restore_cache:
          keys: [install]
      - run:
          name: Run test
          command: |
            npm install
            npm run test

  scan:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - restore_cache:
          keys: [install]
      - run: 
          name: Scan dependencies
          command: |
            npm install
            npm audit

  build:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup
          repo: "${ECR_REPOSITORY_NAME}"
          tag: "${CIRCLE_SHA1}"
          extra_build_args: |
            DATABASE_URL=${DATABASE_URL}
        
workflows:
  default:
    jobs:
      - lint
      - test:
          requires: [lint]
      - scan:
          requires: [test]
      - build:
          requires: [scan]
