version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.0

jobs:
  lint:
    docker:
      - image: circleci/node:16.18.0
    steps:
      - checkout
      - restore_cache:
          keys: [install]
      - run:
          name: Lint app
          command: |
            npm install
            npm run lint
      - save_cache:
          paths: [node_modules]
          key: install
  
  test:
    docker:
      - image: circleci/node:16.18.0
    steps:
      - checkout
      - restore_cache:
          keys: [install]
      - run:
          name: Run test
          command: |
            npm install
            npm run test

  scan:
    docker:
      - image: circleci/node:16.18.0
    steps:
      - checkout
      - restore_cache:
          keys: [install]
      - run: 
          name: Scan dependencies
          command: |
            npm install
            npm audit

  build:
    docker:
      - image: circleci/node:16.18.0
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          name: Build and push image
          repo: "${ECR_REPOSITORY_NAME}"
          tag: "${CIRCLE_SHA1}"
          extra_build_args: |
            DATABASE_URL=${DATABASE_URL}
        
workflows:
  default:
    jobs:
      - lint
      - test:
          requires: [lint]
      - scan:
          requires: [test]
      - build:
          requires: [scan]
