apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-blog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-blog-app
  template:
    metadata:
      labels:
        app: udacity-blog-app
    spec:
      containers:
      - name: udacity-blog-app
        image: 703318274498.dkr.ecr.us-east-1.amazonaws.com/udacity-blog
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: udacity-blog-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: udacity-blog-app